//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBSecond
{
    using System;
    using System.Collections.Generic;
    
    public partial class MFUser
    {
        public int Id { get; set; }
        public string MFUserName { get; set; }
        public System.DateTime DOB { get; set; }
    }
}
