//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_Book
    {
        public int book_id { get; set; }
        public string book_name { get; set; }
        public int book_subcat { get; set; }
        public string book_description { get; set; }
        public string book_publisher { get; set; }
        public string book_edition { get; set; }
        public Nullable<int> book_page { get; set; }
        public int book_price { get; set; }
        public string book_img { get; set; }
        public string book_pdf { get; set; }
    }
}
