//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFLabs
    {
        public int id_lab { get; set; }
        public string lab_name { get; set; }
        public string lab_city { get; set; }
        public int id_analiz { get; set; }
    }
}
