//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFUsers
    {
        public int id_user { get; set; }
        public string user_login { get; set; }
        public string user_pass { get; set; }
        public string user_name { get; set; }
        public int user_role { get; set; }
        public string user_address { get; set; }
    }
}
