//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AT_Laboratorys
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AT_Laboratorys()
        {
            this.AT_Tests = new HashSet<AT_Tests>();
        }
    
        public int LaboratoryID { get; set; }
        public string LaboratoryName { get; set; }
        public int CityID { get; set; }
        public string LaboratoryAddress { get; set; }
        public string LaboratoryPhoneNum { get; set; }
        public string LaboratoryLabeTimins { get; set; }
    
        public virtual AT_Citys AT_Citys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AT_Tests> AT_Tests { get; set; }
    }
}
