//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AT_Tests
    {
        public int TestID { get; set; }
        public string TestName { get; set; }
        public int TestPrice { get; set; }
        public int LaboratoryID { get; set; }
    
        public virtual AT_Laboratorys AT_Laboratorys { get; set; }
    }
}
