//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AT_Users
    {
        public int UserID { get; set; }
        public string UserLogin { get; set; }
        public string UserPassword { get; set; }
        public string UserAddress { get; set; }
        public string UserName { get; set; }
        public string UserPhoneNum { get; set; }
        public byte UserAge { get; set; }
        public byte UserGender { get; set; }
        public int UserRoleID { get; set; }
    
        public virtual AT_Roles AT_Roles { get; set; }
    }
}
