//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class hm_accounts
    {
        public int accountid { get; set; }
        public int accountdomainid { get; set; }
        public byte accountadminlevel { get; set; }
        public string accountaddress { get; set; }
        public string accountpassword { get; set; }
        public int accountactive { get; set; }
        public int accountisad { get; set; }
        public string accountaddomain { get; set; }
        public string accountadusername { get; set; }
        public int accountmaxsize { get; set; }
        public byte accountvacationmessageon { get; set; }
        public string accountvacationmessage { get; set; }
        public string accountvacationsubject { get; set; }
        public byte accountpwencryption { get; set; }
        public byte accountforwardenabled { get; set; }
        public string accountforwardaddress { get; set; }
        public byte accountforwardkeeporiginal { get; set; }
        public byte accountenablesignature { get; set; }
        public string accountsignatureplaintext { get; set; }
        public string accountsignaturehtml { get; set; }
        public System.DateTime accountlastlogontime { get; set; }
        public byte accountvacationexpires { get; set; }
        public System.DateTime accountvacationexpiredate { get; set; }
        public string accountpersonfirstname { get; set; }
        public string accountpersonlastname { get; set; }
    }
}
