//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class hm_aliases
    {
        public int aliasid { get; set; }
        public int aliasdomainid { get; set; }
        public string aliasname { get; set; }
        public string aliasvalue { get; set; }
        public byte aliasactive { get; set; }
    }
}
