//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class hm_dnsbl
    {
        public int sblid { get; set; }
        public int sblactive { get; set; }
        public string sbldnshost { get; set; }
        public string sblresult { get; set; }
        public string sblrejectmessage { get; set; }
        public int sblscore { get; set; }
    }
}
