//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class hm_distributionlistsrecipients
    {
        public int distributionlistrecipientid { get; set; }
        public int distributionlistrecipientlistid { get; set; }
        public string distributionlistrecipientaddress { get; set; }
    }
}
