//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class hm_fetchaccounts
    {
        public int faid { get; set; }
        public byte faactive { get; set; }
        public int faaccountid { get; set; }
        public string faaccountname { get; set; }
        public string faserveraddress { get; set; }
        public int faserverport { get; set; }
        public byte faservertype { get; set; }
        public string fausername { get; set; }
        public string fapassword { get; set; }
        public int faminutes { get; set; }
        public System.DateTime fanexttry { get; set; }
        public int fadaystokeep { get; set; }
        public byte falocked { get; set; }
        public byte faprocessmimerecipients { get; set; }
        public byte faprocessmimedate { get; set; }
        public byte faconnectionsecurity { get; set; }
        public byte fauseantispam { get; set; }
        public byte fauseantivirus { get; set; }
        public byte faenablerouterecipients { get; set; }
    }
}
