//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class hm_fetchaccounts_uids
    {
        public int uidid { get; set; }
        public int uidfaid { get; set; }
        public string uidvalue { get; set; }
        public System.DateTime uidtime { get; set; }
    }
}
