//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class hm_greylisting_whiteaddresses
    {
        public long whiteid { get; set; }
        public string whiteipaddress { get; set; }
        public string whiteipdescription { get; set; }
    }
}
