//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class hm_greylisting_triplets
    {
        public long glid { get; set; }
        public System.DateTime glcreatetime { get; set; }
        public System.DateTime glblockendtime { get; set; }
        public System.DateTime gldeletetime { get; set; }
        public long glipaddress1 { get; set; }
        public Nullable<long> glipaddress2 { get; set; }
        public string glsenderaddress { get; set; }
        public string glrecipientaddress { get; set; }
        public int glblockedcount { get; set; }
        public int glpassedcount { get; set; }
    }
}
