//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class hm_messages
    {
        public long messageid { get; set; }
        public int messageaccountid { get; set; }
        public int messagefolderid { get; set; }
        public string messagefilename { get; set; }
        public byte messagetype { get; set; }
        public string messagefrom { get; set; }
        public long messagesize { get; set; }
        public int messagecurnooftries { get; set; }
        public System.DateTime messagenexttrytime { get; set; }
        public byte messageflags { get; set; }
        public System.DateTime messagecreatetime { get; set; }
        public byte messagelocked { get; set; }
        public long messageuid { get; set; }
    }
}
