//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class hm_messagerecipients
    {
        public long recipientid { get; set; }
        public long recipientmessageid { get; set; }
        public string recipientaddress { get; set; }
        public int recipientlocalaccountid { get; set; }
        public string recipientoriginaladdress { get; set; }
    }
}
