//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class hm_message_metadata
    {
        public long metadata_id { get; set; }
        public int metadata_accountid { get; set; }
        public int metadata_folderid { get; set; }
        public long metadata_messageid { get; set; }
        public Nullable<System.DateTime> metadata_dateutc { get; set; }
        public string metadata_from { get; set; }
        public string metadata_subject { get; set; }
        public string metadata_to { get; set; }
        public string metadata_cc { get; set; }
    }
}
