//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class hm_rule_actions
    {
        public int actionid { get; set; }
        public int actionruleid { get; set; }
        public byte actiontype { get; set; }
        public string actionimapfolder { get; set; }
        public string actionsubject { get; set; }
        public string actionfromname { get; set; }
        public string actionfromaddress { get; set; }
        public string actionto { get; set; }
        public string actionbody { get; set; }
        public string actionfilename { get; set; }
        public int actionsortorder { get; set; }
        public string actionscriptfunction { get; set; }
        public string actionheader { get; set; }
        public string actionvalue { get; set; }
        public int actionrouteid { get; set; }
    }
}
