//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class hm_routes
    {
        public int routeid { get; set; }
        public string routedomainname { get; set; }
        public string routedescription { get; set; }
        public string routetargetsmthost { get; set; }
        public int routetargetsmtport { get; set; }
        public int routenooftries { get; set; }
        public int routeminutesbetweentry { get; set; }
        public byte routealladdresses { get; set; }
        public byte routeuseauthentication { get; set; }
        public string routeauthenticationusername { get; set; }
        public string routeauthenticationpassword { get; set; }
        public byte routetreatsecurityaslocal { get; set; }
        public byte routeconnectionsecurity { get; set; }
        public byte routetreatsenderaslocaldomain { get; set; }
    }
}
