//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class hm_rule_criterias
    {
        public int criteriaid { get; set; }
        public int criteriaruleid { get; set; }
        public byte criteriausepredefined { get; set; }
        public byte criteriapredefinedfield { get; set; }
        public string criteriaheadername { get; set; }
        public byte criteriamatchtype { get; set; }
        public string criteriamatchvalue { get; set; }
    }
}
