//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class hm_securityranges
    {
        public int rangeid { get; set; }
        public int rangepriorityid { get; set; }
        public long rangelowerip1 { get; set; }
        public Nullable<long> rangelowerip2 { get; set; }
        public long rangeupperip1 { get; set; }
        public Nullable<long> rangeupperip2 { get; set; }
        public int rangeoptions { get; set; }
        public string rangename { get; set; }
        public byte rangeexpires { get; set; }
        public System.DateTime rangeexpirestime { get; set; }
    }
}
