//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class hm_sslcertificates
    {
        public long sslcertificateid { get; set; }
        public string sslcertificatename { get; set; }
        public string sslcertificatefile { get; set; }
        public string sslprivatekeyfile { get; set; }
    }
}
