//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class hm_surblservers
    {
        public int surblid { get; set; }
        public byte surblactive { get; set; }
        public string surblhost { get; set; }
        public string surblrejectmessage { get; set; }
        public int surblscore { get; set; }
    }
}
