//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class hm_whitelist
    {
        public long whiteid { get; set; }
        public long whiteloweripaddress1 { get; set; }
        public Nullable<long> whiteloweripaddress2 { get; set; }
        public long whiteupperipaddress1 { get; set; }
        public Nullable<long> whiteupperipaddress2 { get; set; }
        public string whiteemailaddress { get; set; }
        public string whitedescription { get; set; }
    }
}
