//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hMalServerEntities : DbContext
    {
        public hMalServerEntities()
            : base("name=hMalServerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AF_Users> AF_Users { get; set; }
        public virtual DbSet<AFCity> AFCity { get; set; }
        public virtual DbSet<AT_Citys> AT_Citys { get; set; }
        public virtual DbSet<AT_Laboratorys> AT_Laboratorys { get; set; }
        public virtual DbSet<AT_Roles> AT_Roles { get; set; }
        public virtual DbSet<AT_Tests> AT_Tests { get; set; }
        public virtual DbSet<AT_Users> AT_Users { get; set; }
        public virtual DbSet<hm_accounts> hm_accounts { get; set; }
        public virtual DbSet<hm_acl> hm_acl { get; set; }
        public virtual DbSet<hm_aliases> hm_aliases { get; set; }
        public virtual DbSet<hm_blocked_attachments> hm_blocked_attachments { get; set; }
        public virtual DbSet<hm_distributionlists> hm_distributionlists { get; set; }
        public virtual DbSet<hm_distributionlistsrecipients> hm_distributionlistsrecipients { get; set; }
        public virtual DbSet<hm_dnsbl> hm_dnsbl { get; set; }
        public virtual DbSet<hm_domain_aliases> hm_domain_aliases { get; set; }
        public virtual DbSet<hm_domains> hm_domains { get; set; }
        public virtual DbSet<hm_fetchaccounts> hm_fetchaccounts { get; set; }
        public virtual DbSet<hm_fetchaccounts_uids> hm_fetchaccounts_uids { get; set; }
        public virtual DbSet<hm_greylisting_triplets> hm_greylisting_triplets { get; set; }
        public virtual DbSet<hm_greylisting_whiteaddresses> hm_greylisting_whiteaddresses { get; set; }
        public virtual DbSet<hm_group_members> hm_group_members { get; set; }
        public virtual DbSet<hm_groups> hm_groups { get; set; }
        public virtual DbSet<hm_imapfolders> hm_imapfolders { get; set; }
        public virtual DbSet<hm_incoming_relays> hm_incoming_relays { get; set; }
        public virtual DbSet<hm_message_metadata> hm_message_metadata { get; set; }
        public virtual DbSet<hm_messagerecipients> hm_messagerecipients { get; set; }
        public virtual DbSet<hm_messages> hm_messages { get; set; }
        public virtual DbSet<hm_routeaddresses> hm_routeaddresses { get; set; }
        public virtual DbSet<hm_routes> hm_routes { get; set; }
        public virtual DbSet<hm_rule_actions> hm_rule_actions { get; set; }
        public virtual DbSet<hm_rule_criterias> hm_rule_criterias { get; set; }
        public virtual DbSet<hm_rules> hm_rules { get; set; }
        public virtual DbSet<hm_securityranges> hm_securityranges { get; set; }
        public virtual DbSet<hm_servermessages> hm_servermessages { get; set; }
        public virtual DbSet<hm_settings> hm_settings { get; set; }
        public virtual DbSet<hm_sslcertificates> hm_sslcertificates { get; set; }
        public virtual DbSet<hm_surblservers> hm_surblservers { get; set; }
        public virtual DbSet<hm_tcpipports> hm_tcpipports { get; set; }
        public virtual DbSet<hm_whitelist> hm_whitelist { get; set; }
        public virtual DbSet<Operators> Operators { get; set; }
        public virtual DbSet<pn_city> pn_city { get; set; }
        public virtual DbSet<pn_laboratory> pn_laboratory { get; set; }
        public virtual DbSet<pn_roles> pn_roles { get; set; }
        public virtual DbSet<pn_tbl_user> pn_tbl_user { get; set; }
        public virtual DbSet<pn_tests> pn_tests { get; set; }
        public virtual DbSet<Prefixes> Prefixes { get; set; }
        public virtual DbSet<RA_Laboratories> RA_Laboratories { get; set; }
        public virtual DbSet<RA_Roles> RA_Roles { get; set; }
        public virtual DbSet<RA_Tests> RA_Tests { get; set; }
        public virtual DbSet<RA_TestTypes> RA_TestTypes { get; set; }
        public virtual DbSet<RA_Users> RA_Users { get; set; }
        public virtual DbSet<SE_Cities> SE_Cities { get; set; }
        public virtual DbSet<SE_Laboratories> SE_Laboratories { get; set; }
        public virtual DbSet<SE_Roles> SE_Roles { get; set; }
        public virtual DbSet<SE_Users> SE_Users { get; set; }
        public virtual DbSet<Sep_City> Sep_City { get; set; }
        public virtual DbSet<Sep_HistoryTestUser> Sep_HistoryTestUser { get; set; }
        public virtual DbSet<Sep_Laboratory> Sep_Laboratory { get; set; }
        public virtual DbSet<Sep_Role> Sep_Role { get; set; }
        public virtual DbSet<Sep_Test> Sep_Test { get; set; }
        public virtual DbSet<Sep_Users> Sep_Users { get; set; }
        public virtual DbSet<STI_Roles> STI_Roles { get; set; }
        public virtual DbSet<STI_Users> STI_Users { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Checks> Tbl_Checks { get; set; }
        public virtual DbSet<Tbl_Customers> Tbl_Customers { get; set; }
        public virtual DbSet<Tbl_Numbers> Tbl_Numbers { get; set; }
        public virtual DbSet<Tbl_Operators> Tbl_Operators { get; set; }
        public virtual DbSet<Tbl_Prefixes> Tbl_Prefixes { get; set; }
        public virtual DbSet<ZK_Roles> ZK_Roles { get; set; }
        public virtual DbSet<ZK_Users> ZK_Users { get; set; }
        public virtual DbSet<AF_Book> AF_Book { get; set; }
        public virtual DbSet<AFAnaliz> AFAnaliz { get; set; }
        public virtual DbSet<AFLabs> AFLabs { get; set; }
        public virtual DbSet<AFUsers> AFUsers { get; set; }
        public virtual DbSet<book_table> book_table { get; set; }
        public virtual DbSet<hm_dbversion> hm_dbversion { get; set; }
        public virtual DbSet<hm_logon_failures> hm_logon_failures { get; set; }
    }
}
