//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class pn_laboratory
    {
        public int laboratoryID { get; set; }
        public string name { get; set; }
        public Nullable<int> cityID { get; set; }
        public string address { get; set; }
        public string phoneNo { get; set; }
        public string labeTimins { get; set; }
    }
}
