//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class RA_Tests
    {
        public int id { get; set; }
        public string testName { get; set; }
        public int testPrice { get; set; }
        public string description { get; set; }
        public int id_testType { get; set; }
        public int id_Laboratory { get; set; }
    
        public virtual RA_Laboratories RA_Laboratories { get; set; }
        public virtual RA_TestTypes RA_TestTypes { get; set; }
    }
}
