//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class RA_Users
    {
        public int id { get; set; }
        public string fullName { get; set; }
        public int age { get; set; }
        public string address { get; set; }
        public string phoneNumber { get; set; }
        public int gender { get; set; }
        public int id_role { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    }
}
