//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SE_Laboratories
    {
        public int lab_Id { get; set; }
        public string lab_name { get; set; }
        public string lab_adress { get; set; }
        public string lab_PhNo { get; set; }
        public string lab_timings { get; set; }
        public int cityid { get; set; }
    }
}
