//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sep_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sep_Users()
        {
            this.Sep_HistoryTestUser = new HashSet<Sep_HistoryTestUser>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string Adrdress { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Phone { get; set; }
        public string IIN { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sep_HistoryTestUser> Sep_HistoryTestUser { get; set; }
        public virtual Sep_Role Sep_Role { get; set; }
    }
}
