//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sep_HistoryTestUser
    {
        public int HistoryId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> TestId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Sep_Test Sep_Test { get; set; }
        public virtual Sep_Users Sep_Users { get; set; }
    }
}
